Split lvm_snapshots role into separate roles
redhat-cop/infra.lvm_snapshots pull request #40
Opened 2023-12-14 13:28 UTC by ygalblum

Split into three roles - create, revert and remove 
For create allow running only check
Do not use check_for_resize as the functionality was moved to shrink_lv

2023-12-14 13:34 UTC, swapdisk requested changes
Also need to update the Roles section of the main README.

2023-12-14 13:44 UTC, ygalblum commented
> Also need to update the Roles section of the main README.

Done

2024-01-03 22:11 UTC, swapdisk approved these changes
LGTM.

2024-01-03 22:11 UTC, swapdisk commented on roles/create_snapshot/tasks/main.yml
> +    create_snapshot_volumes: "{{ create_snapshot_check_status.stdout | from_json }}"
Right, this failure was because of the ansible issue, not a problem with the role.

2024-01-03 22:12 UTC, merged